controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f 4 4 f f . . . . . 
        . . . . f 5 4 5 5 4 5 f . . . . 
        . . . f e 3 3 3 3 3 3 e f . . . 
        . . f b 3 3 3 3 3 3 3 3 b f . . 
        . . f 3 3 3 3 3 3 3 3 3 3 f . . 
        . f b 3 3 3 3 3 3 3 3 3 3 b f . 
        . f b b 3 3 3 3 3 3 3 3 b b f . 
        . f b b b b b b b b b b b b f . 
        f c b b b b b b b b b b b b f . 
        f b b b b b b b b b b b b c f . 
        f f b b b b b b b b b b c f . . 
        . f c c c f f f f f f f e c . . 
        . . . f b b d b d d e 4 4 e . . 
        . . . f f 1 1 d 1 d e e f . . . 
        . . . . . f b b f f f . . . . . 
        `)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile`, function (sprite, location) {
    tiles.setTileAt(location, sprites.castle.tilePath5)
    fact_check += 1
    if (fact_check == 1) {
        game.showLongText("FACT 1", DialogLayout.Center)
    } else if (fact_check == 2) {
        game.showLongText("FACT 2", DialogLayout.Center)
    } else if (fact_check == 3) {
        game.showLongText("FACT 3", DialogLayout.Center)
    } else if (fact_check == 4) {
        game.showLongText("FACT 4", DialogLayout.Center)
    } else {
        game.showLongText("FACT 5", DialogLayout.Center)
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        . . . f 4 4 f f f f . . . . . . 
        . . f 4 5 5 4 5 f b f f . . . . 
        . . f 5 5 5 5 4 e 3 3 b f . . . 
        . . f e 4 4 4 e 3 3 3 3 b f . . 
        . . f 3 3 3 3 3 3 3 3 3 3 f . . 
        . f 3 3 e e 3 b e 3 3 3 3 f . . 
        . f 3 3 e e e f f 3 3 3 3 f . . 
        . f 3 e e e f b f b b b b f . . 
        . . f e 4 4 f 1 e b b b b f . . 
        . . . f 4 4 4 4 f b b b b f f . 
        . . . f e e e f f f b b b b f . 
        . . . f d d d e 4 4 f b b f . . 
        . . . f d d d e 4 4 e f f . . . 
        . . f b d b d b e e b f . . . . 
        . . f f 1 d 1 d 1 d f f . . . . 
        . . . . f f b b f f . . . . . . 
        `)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        . . . . . . f f f f 4 4 f . . . 
        . . . . f f b f 5 4 5 5 4 f . . 
        . . . f b 3 3 e 4 5 5 5 5 f . . 
        . . f b 3 3 3 3 e 4 4 4 e f . . 
        . . f 3 3 3 3 3 3 3 3 3 3 f . . 
        . . f 3 3 3 3 e b 3 e e 3 3 f . 
        . . f 3 3 3 3 f f e e e 3 3 f . 
        . . f b b b b f b f e e e 3 f . 
        . . f b b b b e 1 f 4 4 e f . . 
        . f f b b b b f 4 4 4 4 f . . . 
        . f b b b b f f f e e e f . . . 
        . . f b b f 4 4 e d d d f . . . 
        . . . f f e 4 4 e d d d f . . . 
        . . . . f b e e b d b d b f . . 
        . . . . f f d 1 d 1 d 1 f f . . 
        . . . . . . f f b b f f . . . . 
        `)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        . . . . . f f 4 4 f f . . . . . 
        . . . . f 5 4 5 5 4 5 f . . . . 
        . . . f e 4 5 5 5 5 4 e f . . . 
        . . f b 3 e 4 4 4 4 e 3 b f . . 
        . . f 3 3 3 3 3 3 3 3 3 3 f . . 
        . f 3 3 e b 3 e e 3 b e 3 3 f . 
        . f 3 3 f f e e e e f f 3 3 f . 
        . f b b f b f e e f b f b b f . 
        . f b b e 1 f 4 4 f 1 e b b f . 
        f f b b f 4 4 4 4 4 4 f b b f f 
        f b b f f f e e e e f f f b b f 
        . f e e f b d d d d b f e e f . 
        . . e 4 c d d d d d d c 4 e . . 
        . . e f b d b d b d b b f e . . 
        . . . f f 1 d 1 d 1 d f f . . . 
        . . . . . f f b b f f . . . . . 
        `)
})
let mySprite: Sprite = null
let fact_check = 0
let textSprite = textsprite.create("Ada Lovelace", 15, 1)
textSprite.setPosition(50, 9)
let adaLovelace = sprites.create(img`
    .............................................................................
    ......................................................db.....................
    ................................................d.dd.dbb.....................
    ................................................bdbccbcbdd...................
    ................................................fccffffcccd..................
    ...............................................ccccccffffcdd..bdd............
    .............................................dbbbcccfffffcecccccb............
    .............................................bbbcffffffffeefffffccb..........
    .........................................ddbbccffffffffffcffffffffc..........
    ......................................dbcccfffffffffffffffffffffffff.........
    ....................................dbcccceccffffceebcffffffffcfffff.........
    ...................................dbccccceeeeeeebe47bbcffffffefcffc.........
    ..................................bbbbbbbbcccce444b444bcffffffeccccc.........
    .................................bcbddddddbbbccebebd7d4bbfffffcffc...........
    ..........................dd...dbcbddddddddbbce4be4bbd4bcfffffcfff...........
    .........................ccccbbbcbdddddddddddfcebb44b747bcfffffffc...........
    ......................dbcffffffceddddddddddddcffedbbd44ebfffffffcc...........
    ......................bcfccffffcbddddddddddddcfffceebeebbfffffffbd...........
    .....................dcffeeffffcbbdddddddddddcffffccffccbcffffffccd..........
    .....................ccfcecffffeeebddddddddddbcffffffffccfffffffffb..........
    ....................dccfccecfffebeebddbbeebbbdeffffcffffffffffffcfcb.........
    ....................dccffcecfffeeeebddbbbbbbbbcffffcfffffffffffffffc.........
    .....................cfffcceccceeccbdddbbeebbbffcccfffffffffffffffcb.........
    .....................bcfffceeeebbbbddddbbcceecffcecffffffccffffffcd..........
    .....................dccfffcceebddddddddbbbbbffcecfffffffcefffffc............
    .......................bcfffcccbdddddddddddbbffffffffffffccfffffb............
    ........................dcfffffbbbdddddddddbbfffffffffffffffffffc............
    .........................dccfffbbbbbddddddbccffffffffffffffffffcb............
    ..........................dbcffbbbebbdddddbccfffffffffffffffcccb.............
    ............................bccbbbbdddddddbfffffffffffffcfffccd..............
    ...............................ebbebbbddddbccfffffffffccfffccc...............
    ...............................ebbebbdddddbccffffffffccffffccc...............
    ...............................cbbbbddddddbeeffffffccffffffccc...............
    ............................dcccbddddddddbbccffffffcfffffffccc...............
    ............................bccccbddddddbbcfffffffccfffffffcff...............
    ............................cccccbbbbbbbbbcfffffccccfffffffccc...............
    ............................ccccccceebbbeffffffccccfffffffffcc...............
    ...........................1cccccccccebcfffffccccccfffffffffcc...............
    ...........................dcccccccccccfffffffcccccffffffffccccbd............
    ...........................bfffccccffffffffffcfccccffffffffcccccb............
    ............................cffcccfffffffffffffccccffffffffcccccc............
    ............................cffffffffffffffffffcbbccfffffffccccccb...........
    ............................cccfffffffffffcfffccbbbcfffffffccccccc...........
    ............................cffffffffffffccfffcccbbcccffffffcccccb...........
    ...........................bcffffffffffcccfffccccbbbccffffffcccccb...........
    ...........................ccfffffffffcccffffccccbbbccffffffcccccd...........
    ..........................bccffffffffcccfffffcbcbbbbccffffffffcccd...........
    .........................dccffffffffcccfffcccbbbbbbbcccfffffffccbd...........
    ........................dcccffffffffcffffccbbbbddccccccfffffffccbb...........
    .......................dcccfffffffffffcccbcccbbddbcbcccfffffffcccb...........
    .......................bccffffffffccccccbcccccbbbbbbcccfffcfffcccb...........
    ......................dccffffffffccccccbdbbccccbbbdbcccffccfffcccbb..........
    ......................ccffffffffccccccbddbbbbcbbbddbcccffccfccfcbbb..........
    .....................bccffffffffccccbbddbbbbbbbddddbcbccffcfccffccc..........
    ....................bccffffffffccccbdddbbbbccbdddddbbbccffcfccffccc..........
    ...................bcccffffffffcccbbddbccccccdbbddddbcccffcfffcfcbcc.........
    ..................dcccfffffffffcbccbdbbccccbbbcccddbccccffcfffcfbdbb.........
    .................dccccfffffffcccccccbbbccccccbccbddbccccffccfffcbdbbb........
    ................dcfccfffffffcccfccbbbccbcfcbbbbcdddbbcccfffffffcbdbbb........
    ................cfccffcffffffffffbbbcfffffcccbccbcdbccccfffffffccbbbbb.......
    ...............bccfcfcfffffffffffcbbcffffffffccfffbcccccffffffffcbcbbc.......
    ...............bccfcccffffffcfffffcccccffffccccfffffffcfffffffffcbcbbc.......
    ...............bcffccfffffffcfffccbcccfffffffccfcfffcfcfffffffffcbbbbb.......
    be.............bfffcffffffffffffcbccfccfffcffbbcffffccffcfffffcccbbbdbb......
    ce4e...........bfffffffffffccffcbbcfffccffbccebcfcffccffffffffffcbdbdbbb.....
    cceecb.........cfccffffffffcccccbcecccbceebbbbbbcbcccffffffffffcccbbddbbd....
    cceeccd.......bcfccfffffffffcccbbbbeebbb444ddb44bbbccffffffffffcccbbddbbb....
    .ceeecb.......bcfccffffffffccccbbbeebbbb444ddd44ebbccffffcccffffccbbddbbb....
    .cceecb1......dcfccffcfffffcccccbbeeebbb444ddb44ebcccfffccccffffcccbbdbbb....
    .cceecb1......dcfccffcfffffcccccbbeeebbb444ddb44ebcccfffccccffffcccbbdbbb....
    .bceeee.......dcfccfccfffffccccffcccfcccbeebbeeeeecbcffcccccfffffccbbbddb....
    .dbdddd.......1cfcccfcccfffffffffccffffccffccffcccccfffccccccccffccbbbbdd....
    ..ddddd........bfcccfccccffffffffccfffffffffffffffffffccfcccccffcccbdbbdd....
    ..dddddddd.....bfcccfccbcffffffcbddbcccccccccccffcffffccfcccccfffcccbbbdd....
    ....ddddddddd..bccccfccdcffffccbdddbcbbbdddddbccccccffcccccccccfffccbccbd....
    ....ddddddddd..dccccffb1bfffcccbddddbddddd1dddbbbcccffcccccccccffffccbccdd...
    ....ddddddddddddccccffb1bffffccccbd1ddddbb111ddd1bccfcdccccccccffffffcbcbd...
    .dbddddddddddddbccccfcb1dcffccccccbcbcdbcbdddbbd1bffcd1bcffccccffffffccccb...
    ..ddbbddddddddddbbccccbd1cffccccffcfffccfbbbbbdddcffc111dbccccccffcffcccbb...
    ...dddddddddddddddddbbdddbffcccffffffffffccffbdbccffc11111ddbbcfccfccccccb...
    ......ce7bdddddddddddddbbbcfcbbfffffffffffffffccfffcb1111111ddcfcccfcccccc...
    ......bce4dddddddddddddddbccbbbffffffccfcffccffffffcd111111111fffcfffccccc...
    .......ccebddddddddddddddddbbbbbccffffffffffffffffcb1111111111cffcffccfccc...
    .......bce4ddddddddddddddddbbcccccffffffffffffffffcd1111111111cfffffcfffcb...
    .......dce4dddddddddddddddbbbcccccfffffffffffffffccd1111111111cfffcffffffc...
    .......1cc4bcccccdbdddddddbccccbbccffffffffffffffcccccbdd11111bffffffffccf...
    ........dee4ccccccbbdcccccbcfccbcfccfffffffffffccccccccccbbd11bcffffffffcc...
    ........1ce4ccccccccccccccccfcccffccfffffffffffffccccccccffceedcfffffffffc...
    .........beeccccccccccccccccfccbcffcfffffffffcffcfcccccccccfffccfffffffffc...
    .........dbecccccccccccccccccccbcffcfffffcfffffffccfccccccccfffffffffffffcc..
    .........dddeccccccccccccccccccbcffccffffccffffffcccffccccccccfffffffffffcc..
    ........ddddbccccccccccccccbcccccffccfffffcffffffcccccfccccccccffffffffffff..
    ........ddbbbccccccfffcccccbbccffffffffcffffffffccffcccfcccfffccffffffffffff.
    ........ddbbeeecffcfffccccccbccffffffffccccfffffccfffcccffccffccffffffffffff.
    ........bbbcceecfccffffceecccffffffffffffffccfffccfffccccffccccccfffffffffffc
    ..........bbcceecfcffffccecccccffffffffffffccffffcffffccccfcccfcccffffffffffc
    ...........bbceecfcffffccecfcccffffffffffffffffffffffffcccffccffcbcfcfffffffc
    ............dccecfcffffceeeccccffffffffffffccffffffcfccccccfffcffcbcffffffffc
    .............bcbcffcfffceeeccbbcfffffffffffffffffffccfcccccfffcffccbcffffffff
    .............dcbbfffffffcbbebddccffffffffffffffffffffffcccccffbcffcbccfffffff
    ..............bcbcffffffccbbbbbccfccffffffffffffcfffffccccbcffceffccbcfffffff
    ..............bcbcffccfcccbbbbbbccfccffffffffffffcfffcccfcccffcbcffcbbcffffff
    ..............dcbbffccccbbcbbbbccccfffffcccfffffffffccccccccccfbbfffcbccfffff
    ..............dccbcfccccbbcbbbbcccccccfccccffffffffccccccfccccfcbcffcbbcffffc
    ..............dccbcffbcbbbbbbbbccceecbbbccfccfcccccccfccbcccccccbbfffcbcfffff
    ..............dccbbcfcccbddbbccdbbeeebbbccccccffcccbccbcbcccccdbdbcffccccffff
    ..............dcccbcfcbcccbbcbbddbbbbbbbccbccccfccbbbbbccbccccddddcffccccffff
    ..............bccccbccbbbccbbccddbbbbbbbcbcccccffccbbbbccbccccbdbbcccccccffff
    ..............ccccccbccccccbbccbdbbbbbbbbbccccccfccbbbbccbbcccbdbbcccccbccfff
    ..............ccccccbcccccccbbbbdbdddbbbbdbccccbffcbddbccbbccccdddcccccbbccff
    ..............ccccccbbcccccccbbccccddbbbd1bccccbcfcbd1dbcbbcffcb1dbccccbbccff
    .............bccccccbcbcccccccccccfccbdd11bccccdbfcbd1ddbbdbcccb1dbccccbbbccf
    .............cccccccbccbccccccccccffcddd11bccccddccbbd1dbbddccccd1bccccccbbcc
    .............ccceebbbccccccccccccccfcbdd11dbbccd1bfcbd1dbdddccccd1dbcccccbbbc
    ............bccecebbbccccccccccccccccbdd11dddccbddccb31dbdddbbccb11dcccccbbbb
    ............beeecebbbbccccccccccccccbbd111dddbbbbdccebddddd1ddfccd1dbccccbcbb
    ............ccecceebbbccccccccccccccfcd1111dddbdbbbccbd11111ddcccd1ddbcccbccb
    ............ccebbeebdbcccccfcccccccccbdd111111ddddbcce3d111111cccb1dbbccccccb
    ............ccebbeebbccccccffcccccccccbdd1111dd11dbcfcbdddddddcccbdddbccbcccb
    ............ccebbeebbcccccccfccfccfccfccb1111dd11dbbccedddddddbccbdddbbbbcccb
    ...........beccbbeebbcccbbccfffccfffcfcfb1ddddd11dbdcfcbdddddddbbdddddbbbcccb
    ...........beccbbeebbbccbcccfffcccfffcffcdddddddddbdbfccbbbddddddddddddbbcccb
    ...........bcecbbeebbbcbcccccfffccfffcffcbdddddddddddcccbbbbddddddddddddccccb
    ...........cccbbbeebdbbbcccccccfcccffffffcddddd1dddddbccbbbbbbdbbbddddddccccb
    ...........ecebdbeebdbbbbccccccffccffccffcddddd1ddddddcccbbbbbbbbbddddddbcbbb
    ...........bcebdbeebdbbbbbcffccffffffffffcbdddddddddddbcccbbbbcbbdddddddbcbbb
    ...........bcebdbeebddbbdbcfffffffffffffccbddddddddbbddcccbbcccbbbddddddbcbbb
    ...........bcebdbcebdddbddbccffffffccffccccbbdddddbbbddbccbbbbbbbbddddddbcbbb
    ..........bbcebdbcebddddddbbcfffffccffcbbccbbd1dddbbbdddcccbbbbbbddd1ddddccbb
    ..........bbccbdbbcbbddddddbbcccffccffccfcbbbddddbbbbbddbccbbbbddddd1ddddbbbb
    ..........bbccddbbcbbddddddddbbfffffffccfccbbdddbbbbbbdddbccbbbbbddd11ddddbbb
    ..........bbecddbbcbbddddddddbbcffffffccfcbdddddbbbbbbdddbccbbbbbbbddddddddbb
    ..........bbccdddbbbbddddddddbbbcccfffccccbddddbbbbbbbbbbbbcbbbbbbbdddddddddb
    ..........bccbdddbbbbddddddddddcbbbcfcbcbbdddddbbbbbcbbbbbbcbbbbbbbdddddddddd
    .........dbccbdddbbbbddddddddddbbcbbbbcccbddddbbbbbbcbbbbbbcbbbbbbddddddddddb
    .........dbccbdddbbbbbdddddddddbbcbdbbcccbddddbbbbbbbbbbbbbbccdbdddbddddddddb
    .........dbccbdddbbbbbdddddddddbcbbbbbbcbddddbbbbbbbbbddbbbbccddbddbdddddddbb
    .........dbbbbddddbbddddddddddddbdbbdbbbdddddbbbbbbbbbbbbbbbccddbddbbdddddddb
    .........bbbbbddddbbdddddddddddddddddbdddddddbbbcbbbbbbbbbbbbbddbdddbdddddddb
    `, SpriteKind.Player)
adaLovelace.setPosition(120, 70)
game.showLongText("My name is Ada Lovelace!", DialogLayout.Bottom)
game.showLongText("I was a brilliant mathematician", DialogLayout.Bottom)
game.showLongText("And am known as the first computer programmer", DialogLayout.Bottom)
game.showLongText("Even before computers were created!", DialogLayout.Bottom)
game.showLongText("Explore the maze to learn about me! And learn all 5 facts!", DialogLayout.Bottom)
sprites.destroy(textSprite)
sprites.destroy(adaLovelace)
tiles.setCurrentTilemap(tilemap`level1`)
fact_check = 0
mySprite = sprites.create(img`
    . . . . . . f f f f 4 4 f . . . 
    . . . . f f b f 5 4 5 5 4 f . . 
    . . . f b 3 3 e 4 5 5 5 5 f . . 
    . . f b 3 3 3 3 e 4 4 4 e f . . 
    . . f 3 3 3 3 3 3 3 3 3 3 f . . 
    . . f 3 3 3 3 e b 3 e e 3 3 f . 
    . . f 3 3 3 3 f f e e e 3 3 f . 
    . . f b b b b f b f e e e 3 f . 
    . . f b b b b e 1 f 4 4 e f . . 
    . f f b b b b f 4 4 4 4 f . . . 
    . f b b b b f f f e e e f . . . 
    . . f b b f 4 4 e d d d f . . . 
    . . . f f e 4 4 e d d d f . . . 
    . . . . f b e e b d b d b f . . 
    . . . . f f d 1 d 1 d 1 f f . . 
    . . . . . . f f b b f f . . . . 
    `, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
controller.moveSprite(mySprite)
tiles.placeOnRandomTile(mySprite, sprites.castle.tileDarkGrass3)
